### ISSUE TITLE
switch language

### ISSUE THREAD

**Issue by conky77** [molsonkiko/JsonToolsNppPlugin#82] opened 2024-10-26 10:19 UTC
I tried N++ 8.7.1  and 8.1 Json Tool.
I tried to switch to English from n++ setting, but the menu is still in Italian.
Nothing changes closing N++
Another plugin HTML tag should change the language, but it doesn't

Notepad++ v8.7.1   (64-bit)
Build time : Oct 25 2024 - 04:07:21
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Home (64-bit)
OS Version : 23H2
OS Build : 22631.4317
Current ANSI codepage : 1252
Plugins : 
    ComparePlus (1.2)
    DSpellCheck (1.5)
    ERPHelper (1.1.2)
    HexEditor (0.9.12)
    HTMLTag (1.5)
    JsonTools (8.1)
    mimeTools (3.1)
    MultiReplace (4.0.0.19)
    NppConverter (4.6)
    NppExport (0.4)
    NPPJSONViewer (2.0.8)
    NppMenuSearch (0.9.6)
    NppPluginOpenHost (1.1)
    PoorMansTSqlFormatterNppPlugin (1.6.13.31508)
    SQLinFormNpp64 (6.24.7.15)
    XMLTools (3.1.1.13)

**Comment by molsonkiko** [comment] 2024-10-28 15:09
@conky77 

Do you mean that JsonTools doesn't immediately change language to match Notepad++ when the user changes the Notepad++ language to Italian (or to English from Italian).  If so, that is expected behavior, as described in the README. JsonTools only translates itself once at startup; it doesn't currently listen to the notification from Notepad++ when it changes language. I didn't add that capability because I felt it was too much of - an increase to the codebase for a change that would not matter most of the time.

If what you mean is that JsonTools doesn't translate itself at all, even at startup, that is a serious bug and I will address it ASAP.

**Comment by conky77** [comment] 2024-10-28 19:24
@molsonkiko 
I confirm that JsonTools doesn't change the menu language at all.
I also tried to execute N++ in administrative mode, but the menu doesn't load the new language at startup. I also tried (with n++ in Italian) to uninstall, clean any files, and reinstall the plugin, but I always got the same result: at startup, the language is always in Italian

Notepad++ v8.7   (64-bit)
Build time : Sep 17 2024 - 17:06:31
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Home (64-bit)
OS Version : 23H2
OS Build : 22631.4317
Current ANSI codepage : 1252
Plugins : 
    ComparePlus (1.2)
    DSpellCheck (1.5)
    ERPHelper (1.1.2)
    HexEditor (0.9.12)
    HTMLTag (1.5)
    JsonTools (8.1)
    mimeTools (3.1)
    MultiReplace (4.0.0.19)
    NppConverter (4.6)
    NppExport (0.4)
    NPPJSONViewer (2.0.8)
    NppMenuSearch (0.9.6)
    NppPluginOpenHost (1.1)
    PoorMansTSqlFormatterNppPlugin (1.6.13.31508)
    SQLinFormNpp64 (6.24.7.15)
    XMLTools (3.1.1.13)

**Comment by molsonkiko** [comment] 2024-10-28 19:38
@conky77 
I'm guessing that your Windows culture is Italian. If the Notepad++ language is unknown, `English`, or not supported, JsonTools checks the user's culture and uses that to set its language if the culture has a supported language.

To check your culture, open PowerShell and enter "get-culture". JsonTools uses `italian.json5` if the first word of the culture name is `Italian`.

I designed JsonTools this way because I thought that some users might not have NPP translated to their native language, and this was the best way I could think of to infer the user's native language independently of NPP. If you think this is a bad idea, I can remove that code. I could also come up with an alternative way for the user to choose their language, but that would almost certainly be more complicated than the current system.

**Comment by conky77** [comment] 2024-10-28 20:37
@molsonkiko 
yes, the get-culture returns it-IT
In my opinion, it should always be possible to use the English version (for example because someone doesn't like the translation, or because I'm using another computer/remote desktop ). Json tools should only check the n++ language. If json tool doesn't have the translation, the English should be shown

**Comment by molsonkiko** [comment] 2024-11-05 05:23
@conky77 

[My latest commit](https://github.com/molsonkiko/JsonToolsNppPlugin/commit/a40137ea030138f0d004cf287911282536587ff4) should fix this issue. [Follow these instructions](https://github.com/molsonkiko/JsonToolsNppPlugin#downloading-unreleased-versions) to download the binary from that commit and see if you're satisfied.

If you don't say you're unsatisfied, I will assume that the issue is fixed by that commit, and I will close this issue about a week after the next release of JsonTools becomes available on the plugin manager.

**Comment by conky77** [comment] 2024-11-08 19:47
> @conky77
> 
> [My latest commit](https://github.com/molsonkiko/JsonToolsNppPlugin/commit/a40137ea030138f0d004cf287911282536587ff4) should fix this issue. [Follow these instructions](https://github.com/molsonkiko/JsonToolsNppPlugin#downloading-unreleased-versions) to download the binary from that commit and see if you're satisfied.
> 
> If you don't say you're unsatisfied, I will assume that the issue is fixed by that commit, and I will close this issue about a week after the next release of JsonTools becomes available on the plugin manager.

I tried it and the language of the menu is ok, but the language of message box seems to follow the language of culture.

the language of menù follows the language of N++
- culture: Italian, N++: Italian, Jsontools:Italian
- culture: Italian, N++: English, Jsontools:English
- culture: Italian, N++: Spanish, Jsontools:English
- culture: Italian, N++: Spanish Argentina, Jsontools:English
- culture: Italian, N++: Venetian, Jsontools:English

With n++ in English, culture Italian, the language of buttons is in Italian
![immagine](https://github.com/user-attachments/assets/fd4fa116-20a1-4fb8-83a4-ac0209f17dd4)



Notepad++ v8.7   (64-bit)
Build time : Sep 17 2024 - 17:06:31
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Home (64-bit)
OS Version : 23H2
OS Build : 22631.4391
Current ANSI codepage : 1252
Plugins : 
    ComparePlus (1.2)
    DSpellCheck (1.5)
    ERPHelper (1.1.2)
    HexEditor (0.9.12)
    HTMLTag (1.5)
    JsonTools (8.1.0.15)
    mimeTools (3.1)
    MultiReplace (4.0.0.19)
    NppConverter (4.6)
    NppExport (0.4)
    NPPJSONViewer (2.0.8)
    NppMenuSearch (0.9.6)
    NppPluginOpenHost (1.1)
    PoorMansTSqlFormatterNppPlugin (1.6.13.31508)
    SQLinFormNpp64 (6.24.7.15)
    XMLTools (3.1.1.13)

**Comment by molsonkiko** [comment] 2024-11-08 20:47
> With n++ in English, culture Italian, message box buttons are in Italian 

C# doesn't offer a reasonably easy way to customize the language of message box buttons, so they just follow the user's culture. I don't think this is a serious enough issue to justify writing hacky low-level code instead of the more compact `System.Windows.Forms.MessageBox.Show` API that I've been using.

**Comment by conky77** [comment] 2024-11-09 07:49
Ok, since it is hard to change the language of the message box, for me this issue is fixed.

**Comment by molsonkiko** [comment] 2024-11-10 03:45
[JsonTools version 8.2](https://github.com/molsonkiko/JsonToolsNppPlugin/releases/tag/v8.2), incorporating a fix for this issue, is now live. I will soon submit a PR to include v8.2 in the plugins manager.

**Comment by molsonkiko** [comment] 2024-12-01 21:02
No apparent regression since v8.2 was available on the Plugins Admin for NPP 8.7.2, so closing this issue.

**Closed by molsonkiko** 2024-12-01 21:02 UTC
Labels: probably fixed?
