### ISSUE TITLE
Is there a way to turn off error correction?

### ISSUE THREAD

**Issue by GTGeek88** [molsonkiko/JsonToolsNppPlugin#51] opened 2023-11-27 17:01 UTC
In trying to troubleshoot some JSON I'm sending to a website, I find that the pretty-print feature is handy, but not when it corrects errors. Granted, you have the (not always real visible) error reporting section, but I'd really rather not have it insert a comma where one did not exist. You can continue the pretty-print as if it was there, but just don't show it. Hopefully, I'm just missing a setting, because I really don't like it fixing what I did not have right to begin with. It doesn't help when I'm trying to find errors. Granted, maybe I should just look at the errors (a feature which I had overlooked until recently), but I think doing both is preferable (since your code could potentially miss something, too).

**Comment by molsonkiko** [comment] 2023-11-27 18:39
I'm not particularly inclined to implement a pretty-printing method that
deliberately leaves errors in the JSON. As you yourself noted, the error
form exists if you want to manually correct errors. If you're
pretty-printing to make JSON more readable, you could:
- Copy the document, paste in a new empty file, pretty-print that
- use the treeview (it can be opened without reformatting the file)

**Comment by molsonkiko** [comment] 2023-11-27 23:38
Since it's not even really clear to me what you're asking for, and I have no intention of implementing what I *think* you're asking for, I'm closing this issue.

**Closed by molsonkiko** 2023-11-27 23:38 UTC

**Comment by molsonkiko** [comment] 2023-11-28 04:05
> In my case, the error caused the treeview to not highlight the proper nodes in the JSON, even though it seemed to otherwise understand the structure. 

I didn't realize that you had an error in your JSON that was causing JsonTools to fail to parse your file. 
### If you are asking me to improve the parser, *I would be happy to help*, but you will have to give me an example so I can understand what the issue is.

> I didn't think of your plug-in as an error corrector. I did think of it as formatting what I gave it (as best it could), warts and all.

__You have a fundamental misconception of how the pretty-printing and compression my plugin works. Allow me to clarify some things.__

When my plugin pretty-prints or compresses your JSON, there are two separate stages:
1. my plugin __parses the JSON__ and creates a hierarchy of C# objects that represent the abstract structure of the file. During this stage, the parser notes any errors it sees, but __the objects it uses to represent the file's structure don't know anything about the errors recognized by the parser.__
2. my plugin uses the objects that represent the file's structure to output formatted text according to a compression or pretty-printing algorithm. __When the plugin is pretty-printing or compressing the JSON, all that it knows is the abstract structure of the file. It has completely forgotten how the file was formatted before pretty-printing or compression.__

It's *not impossible* to format a JSON in a way that remembers how the JSON was previously formatted, but it's a *very hard problem*, one that would require much more time than I want to invest in something that I regard as unimportant.

**Comment by molsonkiko** [comment] 2023-11-28 18:04
This doesn't address all of the things you were dissatisfied about, but I've just made a change (available in the next release) that will make it so that a prompt asking if you want to see the error form is ON by default. There is a setting that controls this, but it was previously off by default because I thought people might find the prompt irritating.

**Comment by GTGeek88** [comment] 2023-11-28 22:36
Thank you. My apologies for not responding, yet. Busy day with an upcoming deadline.RussellSent from my iPhoneOn Nov 28, 2023, at 4:40 PM, molsonkiko ***@***.***> wrote:﻿
As a continued show of goodwill and interest in solving your problem, I have greatly improved the parser's handling of certain errors.
If your JSON had an error like this:
[
    {"a": 1, "b": "foo", // woops! missing a close '}' here
    {"a": 2, "b": "baz"}
]

previously JsonTools would fail completely and do something inappropriate.
My next release will correctly parse that JSON as [{"a":1,"b":"foo"},{"a":2,"b":"baz"}] as expected.

**Comment by molsonkiko** [comment] 2023-12-01 23:07
No message would appear there; that comment was just for illustrative purposes (although Notepad++ actually does allow showing inline messages like that, though I don't know exactly how). If you pretty-printed the document, the missing `}` would be inserted

This type of error (missing `}` or `]` in the middle of the document) could get one of any number of different error messages, depending on how exactly you make the error. This is because __if a document contained a mistake, it's very hard to know exactly what they intended, and thus it is also hard to say with certainty what type of mistake they made.__

In lieu of further explanation, I'll just show you what errors are shown on the error form using my current (un-released) version of JsonTools on the example document.

![image](https://github.com/molsonkiko/JsonToolsNppPlugin/assets/46202915/a2fd862b-e1cd-4eab-86ec-f52c758bf26b)

The error messages are a bit confusing, but VSCode did a worse job of parsing the same JSON with even less useful error messages, so I figure that's a point in my favor.

**Comment by GTGeek88** [comment] 2023-12-02 00:13
Ok, thanks for the dialog on this. If  you're doing a better job of parsing the JSON than VSCode, I guess that is good.
