### ISSUE TITLE
[Check JSON syntax now] clear (Syntax errors in JSON) pane upon no errors found

### ISSUE THREAD

**Issue by emanueol** [molsonkiko/JsonToolsNppPlugin#80] opened 2024-09-27 11:50 UTC
Example:
1. have some json error(s) on the editor
2. execute option [Check JSON syntax now]
3. ok: bottom popup "Syntax errors in JSON" shows errors.
4. fix errors on editor
5. execute again option [Check JSON syntax now]
6. nok: bottom popup "Syntax errors in JSON" still showing previous errors. 

Would be nice to at least clear "Syntax errors in JSON" pane.
![Check JSON syntax now  clear (Syntax errors in JSON) pane upon no errors found](https://github.com/user-attachments/assets/834ae2d9-4a62-45fd-9fa0-b57162d08094)

and/or add success No errors found (in beautiful green color) :)

**Comment by molsonkiko** [comment] 2024-09-27 18:19
Thanks for reporting this issue, @emanueol !

This issue should be addressed by [this commit](https://github.com/molsonkiko/JsonToolsNppPlugin/actions/runs/11075572042). You can follow steps 5-8 of my [instructions for downloading unreleased versions](https://github.com/molsonkiko/JsonToolsNppPlugin#downloading-unreleased-versions) to test the commit. If that commit fixes your issue, you can keep using the new version of `JsonTools.dll`.

**Comment by molsonkiko** [comment] 2024-11-10 03:45
[JsonTools version 8.2](https://github.com/molsonkiko/JsonToolsNppPlugin/releases/tag/v8.2), incorporating a fix for this issue, is now live. I will soon submit a PR to include v8.2 in the plugins manager.

**Comment by emanueol** [comment] 2024-11-10 19:29
> [JsonTools version 8.2](https://github.com/molsonkiko/JsonToolsNppPlugin/releases/tag/v8.2), incorporating a fix for this issue, is now live. I will soon submit a PR to include v8.2 in the plugins manager.

1. Notepad++ > Plugins Admin > showed me a version 8.1 of JsonTools (so seems you 8.2 still not available automatically).
2. So then I wanted to check status of Plugins Admin, googled for "notepad++ plugin manager" but found a repo that seems discontinued [https://github.com/bruderstein/nppPluginManager] "(..)(ATTENTION: This plugin is not actively supported since 2019. The webservice to host the plugin list was stopped. Please use the built-in solution of N++.(..)".

So I suppose, when you say "(..) I will soon submit a PR to include v8.2 in the plugins manager.(..)" what does that mean ?
What will bring your 8.2 available automatically to me, is this the right sequence:
```JsonTools 8.2 --> open PR on plugins manager (whats repo link?) --> and Notepad++ repo build automatically brings in plugins manager which shall have your JsonTools in a list as UPDATES ?
```
JsonTools repo: https://github.com/molsonkiko/JsonToolsNppPlugin
plugins manager repo: ????
Notepad++ repo: I guess its this one ? https://github.com/notepad-plus-plus/notepad-plus-plus ?

Thanks

**Comment by molsonkiko** [comment] 2024-11-10 19:45
@emanueol 

Sorry if my previous post wasn't clear. In the image you showed above, the Plugins Admin for Notepad++ v8.7 lists JsonTools v8.1 as the most recent version because that was the last version I had told [the nppPluginList GitHub repo](https://github.com/molsonkiko/nppPluginList) about when Notepad++ v8.7 was released. The Plugins Admin has no way to check what is the most recent version of a plugin; it lists a static snapshot of the most recent versions that the plugin maintainer told them about.

I just told the nppPluginList about JsonTools v8.2, but Notepad++ v8.7.1 has already released, which means that you won't be able to download JsonTools v8.2 via the Plugins Admin until Notepad++ v8.7.2 at the earliest.

However, it is relatively easy to update JsonTools to v8.2 by following these steps:
1. Download the zip archive of JsonTools v8.2 from the [release page](https://github.com/molsonkiko/JsonToolsNppPlugin/releases/tag/v8.2)
2. Extract the folder in that archive and rename it to JsonTools.
3. Replace the contents of the JsonTools plugin folder for your Notepad++ installation with the contents of the downloaded folder.

By following those steps, you're just doing what Notepad++ does when you use the Plugins Admin, except manually rather than through a GUI.

**Comment by molsonkiko** [comment] 2024-12-01 21:04
No apparent regression since v8.2 was available on the Plugins Admin for NPP 8.7.2, so closing this issue.

**Closed by molsonkiko** 2024-12-01 21:04 UTC
Labels: bug, probably fixed?
