### ISSUE TITLE
Advanced Options in Search/Replace Form are half way cut off on screen with higer resolution

### ISSUE THREAD

**Issue by axdu** [molsonkiko/JsonToolsNppPlugin#79] opened 2024-09-12 10:37 UTC
Great tool what I have seen and tried so far. Now I wanted to try the advanced search feature but am stuck with unreachable options.
This is how it looks:
![image](https://github.com/user-attachments/assets/07d35a51-85ed-4de3-acc6-9c86ad9eb7d0)

The problem could be caused by the non adapting size of the rectangular box that surrounds the advanced options.
It's not a major problem. But I am tempted to set 
private const int ADVANCED_CONTROLS_EXTENDED_HEIGHT = 163; 
To a higher value. ( in FindReplaceForm.cs )
Unfortunately I have no idea how to compile JsonTools.dll

Win10 screen resolution 3840x2160 200% on size of text / apps and other elements. Changing to another % setting didn't help.
Debug:
Notepad++ v8.6.9   (32-bit)
Build time : Jul 12 2024 - 05:08:26
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.4780
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2)
    FWDataViz (1.4.2)
    HexEditor (0.9.12)
    JsonTools (8)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExec (0.6.2)
    NppExport (0.4)
    NppXmlTreeviewPlugin (2)
    PreviewHTML (1.3.2)
    XMLTools (3.1.1.13)

**Comment by molsonkiko** [comment] 2024-09-12 19:10
Hi @axdu , thanks for reporting this bug. I was able to replicate the issue on my machine, and I think my latest commit fixes it.

You should be able to test my fix by doing the following:
1. Go to [the Github Actions artifacts page for my latest commit](https://github.com/molsonkiko/JsonToolsNppPlugin/actions/runs/10836923153)
2. Download the `plugin_dll_x86` artifact (that contains the 32-bit build of JsonTools)
3. Extract the folder named `plugin_dll_x86` inside the zip file you downloaded.
4. Inside the extracted folder is `JsonTools.dll`, the 32-bit build of the code from my latest commit.
5. Close Notepad++
6. Replace the `JsonTools.dll` file in your plugin folder with the new `JsonTools.dll`. You may wish to rename the old DLL to `JsonTools 8p0.dll` before doing this, so that you can still go back to JsonTools 8.0 if you prefer.
7. Re-open Notepad++ and see if the issue is still present.

If you're satisfied with the fix, you can just keep using the new DLL.

**Comment by axdu** [comment] 2024-09-12 22:07
Hi @molsonkiko , 
you are so committed! Thank you very much it works like a charm. 
![image](https://github.com/user-attachments/assets/a87fa7ba-8614-447f-9d00-ac7a0ae56c44)

**Comment by molsonkiko** [comment] 2024-09-12 22:29
@axdu 
Glad to hear the new version works better! I'm going to follow my usual policy of leaving this issue open for a while, then closing it when the next version of JsonTools that's available on the Plugin Manager implements this fix.

**Comment by molsonkiko** [comment] 2024-11-10 03:45
[JsonTools version 8.2](https://github.com/molsonkiko/JsonToolsNppPlugin/releases/tag/v8.2), incorporating a fix for this issue, is now live. I will soon submit a PR to include v8.2 in the plugins manager.

**Comment by molsonkiko** [comment] 2024-12-01 21:03
No apparent regression since v8.2 was available on the Plugins Admin for NPP 8.7.2, so closing this issue.

**Closed by molsonkiko** 2024-12-01 21:03 UTC
Labels: bug, probably fixed?
